import { EXTENSION_NAME } from "./ext.constants";

export const CLASS_INNER_CODE_KEY = "innerCode";
export const CLASS_INNER_CLASSES_KEY = "innerClasses";
export const CLASS_DEFINITION_TEMPLATE_KEY = "className";
export const CLASS_DEFINITION_CONSTRUCTER_KEY = "classConstructor";

export const ASSET_VARIABLE_KEY = "variableName";
export const ASSET_VARIABLE_VALUE = "variableValue";

export const INNER_CLASS_TYPE_KEY = "innerClassType";
export const INNER_CLASS_NAME_KEY = "innerClassName";

export const IGNORED_LINTS =
  `// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field\n` +
  `import 'package:flutter/foundation.dart';\n\n`;

export const GENERATED_TEMPLATE =
  `//\n` +
  `// GENERATED CODE - DO NOT MODIFY BY HAND\n` +
  `// **************************************************************************\n` +
  `// Generated by ${EXTENSION_NAME} extension for VS Code\n` +
  `// @mrasityilmaz\n` +
  `// **************************************************************************\n\n`;

export const CLASS_DEFINITION_TEMPLATE =
  `@immutable\n` +
  `final class ${CLASS_DEFINITION_TEMPLATE_KEY} {\n` +
  `  const ${CLASS_DEFINITION_CONSTRUCTER_KEY}._();\n` +
  `${CLASS_INNER_CLASSES_KEY}\n` +
  `${CLASS_INNER_CODE_KEY}\n` +
  `}\n\n`;

export const INNER_CLASS_TEMPLATE = `  static final ${INNER_CLASS_TYPE_KEY} ${INNER_CLASS_NAME_KEY} = ${INNER_CLASS_TYPE_KEY}._();\n`;
export const S_C_S_VARIABLE_TEMPLATE = `  static const String ${ASSET_VARIABLE_KEY} = '${ASSET_VARIABLE_VALUE}';\n`;
export const F_VARIABLE_TEMPLATE = `  final String ${ASSET_VARIABLE_KEY} = '${ASSET_VARIABLE_VALUE}';\n`;
